title: Godspeed Project
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://john-fatboygarage/github.io/GodspeedProject/

aux_links:
  Template Repository: https://github.com/john-fatboygarage/GodspeedProject
